icons=open('scripts/icons.json').read()
html=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>staves</title>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{--b0:#0f1211;--b1:#171b1a;--b2:#1e2322;--b3:#262c2a;--b4:#303735;--line:#2b3230;--line2:#3a4340;--t1:#eef1ee;--t2:#bcc4c0;--t3:#8a9490;--acc:#f0a35e;--accbg:rgba(240,163,94,.14);--agent:#4fcb92;--agentbg:rgba(79,203,146,.12);--alert:#e5484d;--alertbg:rgba(229,72,77,.14);--person:#d9c9a6;--outside:#8fa3b8;--system:#8d9791}
*{box-sizing:border-box}html,body{height:100%;margin:0;background:var(--b0);color:var(--t1);font:12.5px/1.45 Archivo,system-ui,sans-serif;-webkit-font-smoothing:antialiased;overflow:hidden}
button{font:inherit;color:inherit;background:none;border:0;padding:0;cursor:pointer}input,textarea{font:inherit;color:inherit}
svg.ic{width:16px;height:16px;fill:currentColor;flex:none;vertical-align:-3px}
::-webkit-scrollbar{width:10px;height:10px}::-webkit-scrollbar-thumb{background:var(--b4);border:3px solid var(--b1);border-radius:6px}
/* frame */
#ws{display:grid;grid-template-rows:44px 1fr 4px 300px;grid-template-columns:300px 4px 1fr;height:100%;gap:0}
.panel{background:var(--b1);display:flex;flex-direction:column;min-height:0;min-width:0}
.ph{height:34px;display:flex;align-items:center;gap:8px;padding:0 8px 0 12px;background:var(--b2);border-bottom:1px solid var(--line);font-size:12px;font-weight:600;color:var(--t2);flex:none}.ph .grow{flex:1}.ph .ib{width:26px;height:26px}
.ib{width:30px;height:30px;display:inline-grid;place-items:center;border-radius:5px;color:var(--t2)}.ib:hover{background:var(--b3);color:var(--t1)}.ib.on{background:var(--acc);color:#1a1208}.ib.warn{color:var(--alert)}
.seg{display:inline-flex;background:var(--b3);border-radius:6px;padding:2px;gap:2px}.seg .ib{width:32px;height:26px;border-radius:4px}
[data-tip]{position:relative}[data-tip]:hover::after{content:attr(data-tip);position:absolute;top:calc(100% + 7px);left:50%;transform:translateX(-50%);background:#000;color:#fff;font-size:11px;padding:5px 8px;border-radius:4px;white-space:nowrap;z-index:99;pointer-events:none}
.gutter{background:var(--b0)}
/* top */
#top{grid-column:1/-1;display:flex;align-items:center;gap:8px;padding:0 12px;background:var(--b1);border-bottom:1px solid var(--line)}
#top .logo{width:26px;height:26px;display:grid;place-items:center;color:var(--acc);margin-right:4px}
#top .name{font-weight:600;font-size:13px;display:flex;align-items:center;gap:6px;padding:6px 8px;border-radius:5px}#top .name:hover{background:var(--b3)}#top .name svg{width:12px;height:12px;color:var(--t3)}
#top .grow{flex:1}
.meter{display:inline-flex;align-items:center;gap:6px;height:28px;padding:0 10px;border-radius:5px;color:var(--t2);font-variant-numeric:tabular-nums;font-size:12px}.meter b{color:var(--t1);font-weight:600}.meter svg{width:14px;height:14px}
.badge{position:absolute;top:-4px;right:-4px;min-width:16px;height:16px;padding:0 4px;border-radius:8px;background:var(--alert);color:#fff;font-size:10px;font-weight:700;display:grid;place-items:center}
.rec{width:8px;height:8px;border-radius:50%;background:var(--t3)}.rec.on{background:var(--agent);box-shadow:0 0 0 3px var(--agentbg)}
/* outline */
#ol{grid-row:2}#ol .body{overflow:auto;padding:6px 0 40px;flex:1}
.row{display:flex;align-items:center;gap:6px;height:28px;padding:0 8px 0 var(--ind);color:var(--t2);cursor:pointer;position:relative;user-select:none}
.row:hover{background:var(--b2);color:var(--t1)}.row.sel{background:var(--accbg);color:var(--t1)}.row.sel::before{content:"";position:absolute;left:0;top:0;bottom:0;width:2px;background:var(--acc)}
.row .tw{width:14px;height:14px;display:grid;place-items:center;color:var(--t3);flex:none}.row .tw svg{width:10px;height:10px;transition:transform 120ms}.row.open .tw svg{transform:rotate(90deg)}
.row>svg.k{width:15px;height:15px;color:var(--t3)}.row.who>svg.k{color:var(--person)}.row.who.agent>svg.k{color:var(--agent)}.row.who.outside>svg.k{color:var(--outside)}.row.who.system>svg.k{color:var(--system)}
.row .n{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.row.who .n{font-weight:600;color:var(--t1)}.row.job .n{font-weight:500;color:var(--t1)}.row.task .n{font-size:12px}.row.leaf .n{font-size:11.5px;color:var(--t3)}
.row .m{display:flex;gap:4px;align-items:center;color:var(--t3);font-size:11px}.row .m .pg{width:7px;height:9px}.row .m .cnt{color:var(--alert);font-weight:600}.row .m .q{color:var(--t2);font-weight:700}
.row .add{opacity:0;width:22px;height:22px;display:grid;place-items:center;border-radius:4px;color:var(--t3)}.row:hover .add{opacity:1}.row .add:hover{background:var(--b3);color:var(--t1)}.row .add svg{width:12px;height:12px}
.row.drag-over{box-shadow:inset 0 0 0 1px var(--acc)}.row.drag-after{box-shadow:inset 0 -2px 0 var(--acc)}
.pg{display:inline-block;width:8px;height:11px;border:1px solid var(--t3);position:relative;flex:none;border-radius:1px}.pg::after{content:"";position:absolute;left:0;right:0;bottom:0;background:var(--t2);height:var(--cov)}
/* stage */
#stage{grid-row:2;grid-column:3;position:relative}
#stage .sh{padding:22px 32px 16px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:1fr auto;gap:16px;align-items:start}
#stage h2{margin:0 0 6px;font-size:22px;font-weight:700;letter-spacing:-.02em;display:flex;align-items:center;gap:10px;line-height:1.2}#stage h2 svg{width:20px;height:20px;color:var(--t2)}
#stage .crumb{font-size:11.5px;color:var(--t3);margin-bottom:8px;display:flex;gap:6px;align-items:center}#stage .crumb b{font-weight:500;color:var(--t3);cursor:pointer}#stage .crumb b:hover{color:var(--t1)}#stage .crumb svg{width:10px;height:10px}
#stage .sub{color:var(--t2);font-size:13.5px;max-width:70ch;margin:0 0 12px}#stage .sub.q{color:var(--t3);cursor:pointer}
.chips{display:flex;gap:6px;flex-wrap:wrap}.chip{display:inline-flex;align-items:center;gap:6px;height:28px;padding:0 10px 0 8px;border-radius:14px;background:var(--b3);font-size:12.5px;color:var(--t1);cursor:pointer;border:1px solid transparent}.chip:hover{border-color:var(--line2);color:var(--t1)}.chip svg{width:13px;height:13px;color:var(--t3)}.chip b{font-weight:600;color:var(--t1)}.chip.q{background:transparent;border:1px dashed var(--line2);color:var(--t3)}.chip.alert{color:var(--alert)}.chip.alert svg{color:var(--alert)}
#stage .right{display:flex;flex-direction:column;align-items:flex-end;gap:10px}#stage .right .rowb{display:flex;gap:6px;position:relative}
#stage .body{overflow:auto;padding:22px 32px 32px;flex:1}
.chain{display:flex;gap:10px;align-items:stretch;overflow-x:auto;padding:4px 2px 12px}
.card{width:220px;min-width:220px;min-height:136px;padding:14px 14px 10px;background:var(--b2);border:1px solid var(--line);border-radius:8px;position:relative;cursor:pointer;display:flex;flex-direction:column;transition:border-color 100ms,transform 100ms}.card:hover{border-color:var(--line2);transform:translateY(-1px)}.card.sel{border-color:var(--acc);box-shadow:0 0 0 1px var(--acc)}
.card .big{width:30px;height:30px;border-radius:7px;background:var(--b3);display:grid;place-items:center;color:var(--t2);margin-bottom:10px}.card .big svg{width:16px;height:16px}.card .h{font-weight:600;font-size:13px;line-height:1.3}.card .k{font-size:11.5px;color:var(--t2);margin:2px 0 8px}
.card .tools{display:flex;flex-wrap:wrap;gap:6px 10px}.card .tool{font-size:11px;color:var(--t2);display:inline-flex;align-items:center;gap:5px}.card .w{margin-top:8px;font-size:11px;color:var(--alert);display:flex;gap:5px;align-items:center}.card .w svg{width:12px;height:12px}
.card .foot{margin-top:auto;display:flex;gap:6px;align-items:center;padding-top:8px;font-size:11px;color:var(--t3)}
.card.new{border-style:dashed;background:transparent;min-width:48px;width:48px;display:grid;place-items:center;color:var(--t3)}.card.new:hover{color:var(--t1)}
.splitter{width:22px;min-width:22px;display:grid;place-items:center;color:transparent;cursor:col-resize;position:relative}.splitter:hover{color:var(--acc)}.splitter::before{content:"";position:absolute;left:50%;top:10px;bottom:10px;width:1px;background:var(--line)}.splitter:hover::before{background:var(--acc)}.splitter svg{position:relative;width:14px;height:14px;background:var(--b1);border-radius:3px}
.acct{margin-top:14px;padding-top:14px;border-top:1px solid var(--line);display:flex;gap:28px;flex-wrap:wrap}.acct .f{min-width:200px}.acct label{display:block;font-size:11px;color:var(--t3);margin-bottom:3px}.acct .v{color:var(--t1)}.acct .v.q{color:var(--t3);border:1px dashed var(--line2);padding:5px 8px;border-radius:5px;display:inline-block;cursor:pointer}.acct .quote{color:var(--t3);font-size:11.5px;border-left:2px solid var(--line2);padding-left:8px;margin-top:5px;max-width:52ch}
/* issues & instructions */
.issues,.instr{margin-top:16px;border:1px solid var(--line);border-radius:8px;background:var(--b2);overflow:hidden}
.ih{display:flex;align-items:center;gap:8px;height:34px;padding:0 12px;background:var(--b3);font-size:12px}.ih svg{width:14px;height:14px;color:var(--t2)}.ih b{font-weight:600}.ih .path{color:var(--t3);font-family:ui-monospace,Menlo,monospace;font-size:11.5px}.ih .grow{flex:1}.ih .ro{font-size:11px;color:var(--t3);display:inline-flex;gap:5px;align-items:center}
.iss{display:flex;align-items:flex-start;gap:10px;padding:9px 12px;border-top:1px solid var(--line);font-size:12.5px}.iss>svg{margin-top:2px}.iss .ans{margin-top:6px;display:flex;gap:8px;align-items:flex-start;color:var(--t2);font-size:12px;line-height:1.45;padding:8px 10px;background:var(--b3);border-radius:6px}.iss .ans svg{width:14px;height:14px;color:var(--agent);margin-top:2px;flex:none}.iss .ans b{color:var(--t1)}.iss .st{margin-top:2px}.ih .cnt{font-size:11px;color:var(--t3);margin-left:6px}
.raise{display:flex;align-items:center;gap:10px;padding:8px 12px;border-top:1px solid var(--line);background:var(--b1)}.raise svg{width:14px;height:14px;color:var(--t3)}.raise input{flex:1;background:none;border:0;outline:0;color:var(--t1);font-size:12.5px}.raise .k{font-size:11px;color:var(--t3);border:1px solid var(--line2);border-radius:4px;padding:1px 5px}.iss svg{width:14px;height:14px;color:var(--t3)}.iss .t{flex:1}.iss .st{font-size:11px;color:var(--t3);padding:2px 8px;border-radius:10px;background:var(--b3)}.iss.raised svg{color:var(--t2)}.iss.raised .st{color:var(--t2)}.iss.picked-up svg{color:var(--agent)}.iss.picked-up .st{color:var(--agent)}.iss.proposed svg{color:var(--agent)}.iss.proposed .st{background:var(--agentbg);color:var(--agent)}
.instr .sum{padding:10px 12px 0;color:var(--t2);font-size:12.5px}.instr pre{margin:8px 12px 12px;padding:12px;background:var(--b1);border:1px solid var(--line);border-radius:6px;font:11.5px/1.55 ui-monospace,Menlo,monospace;color:var(--t2);white-space:pre-wrap;max-height:220px;overflow:auto}
/* review screen */
#rv{position:fixed;inset:0;z-index:70;background:var(--b0);display:none;overflow:auto}#rv.show{display:block}
#rv .wrap{max-width:980px;margin:0 auto;padding:56px 32px 80px}#rv .eyebrow{font-size:12px;color:var(--t3);margin-bottom:8px;display:flex;gap:8px;align-items:center}#rv h1{margin:0 0 6px;font-size:30px;font-weight:700;letter-spacing:-.025em}#rv .lead{color:var(--t2);font-size:15px;margin:0 0 28px;max-width:70ch}
#rv .facts{display:flex;gap:10px;margin:0 0 28px}#rv .fact{display:flex;align-items:center;gap:10px;padding:12px 16px;background:var(--b2);border:1px solid var(--line);border-radius:8px}#rv .fact svg{width:18px;height:18px;color:var(--t2)}#rv .fact b{font-size:20px;font-weight:700}#rv .fact span{color:var(--t3);font-size:12px}
#rv .sec{display:grid;grid-template-columns:260px 1fr;gap:24px;padding:22px 0;border-top:1px solid var(--line)}#rv .sec h3{margin:0 0 4px;font-size:15px;display:flex;align-items:center;gap:8px}#rv .sec h3 svg{width:16px;height:16px}#rv .sec .why{color:var(--t3);font-size:12px}#rv .sec.surprise h3 svg{color:var(--acc)}#rv .sec.blind h3 svg{color:var(--alert)}#rv .sec.words h3 svg{color:var(--outside)}#rv .sec.first h3 svg{color:var(--agent)}
#rv .item{display:flex;align-items:center;gap:12px;padding:10px 12px;background:var(--b2);border:1px solid var(--line);border-radius:7px;margin-bottom:6px;cursor:pointer}#rv .item:hover{border-color:var(--line2)}#rv .item .n{font-weight:600;min-width:180px}#rv .item .d{flex:1;color:var(--t2)}#rv .item .go{color:var(--t3);font-size:11px;display:inline-flex;gap:4px;align-items:center}#rv .item svg{width:13px;height:13px}
#rv .mini{margin:0 0 20px;padding:14px 16px;background:var(--b2);border:1px solid var(--line);border-radius:10px}#rv .mini .row{display:flex;align-items:center;gap:10px;height:34px}#rv .mini .row .who{width:120px;font-size:11px;color:var(--t2);display:flex;gap:6px;align-items:center;white-space:nowrap;overflow:hidden}#rv .mini .row .who svg{width:12px;height:12px}#rv .mini .lane{flex:1;position:relative;height:22px;border-top:1px dashed var(--line)}#rv .mini .c{position:absolute;top:2px;height:18px;padding:0 8px;font-size:10.5px;font-weight:600;background:var(--b3);border:1px solid var(--line2);border-left:3px solid var(--c);border-radius:3px;white-space:nowrap;display:flex;align-items:center;gap:6px}#rv .mini .c i{width:12px;height:12px;border-radius:6px;background:var(--alert);color:#fff;font-size:8px;font-style:normal;display:grid;place-items:center}#rv .mini .c.q::before{content:'?';position:absolute;left:-7px;top:-7px;width:12px;height:12px;border-radius:6px;background:var(--acc);color:#1a1208;font-size:8px;font-weight:800;display:grid;place-items:center}
#rv .cta{display:flex;gap:10px;margin-top:28px;align-items:center}#rv .cta .hint{color:var(--t3);font-size:12px;margin-left:auto;font-family:ui-monospace,Menlo,monospace}
/* focus banner */
#fb{display:none;align-items:center;gap:10px;height:30px;padding:0 12px;background:var(--accbg);border-bottom:1px solid var(--line);font-size:12px;color:var(--t1)}#fb.show{display:flex}#fb b{color:var(--acc)}#fb .grow{flex:1}#fb button{color:var(--t2);display:inline-flex;gap:6px;align-items:center}#fb button svg{width:13px;height:13px}
/* ask drawer */
#ask{position:absolute;top:0;right:0;bottom:0;width:380px;background:var(--b2);border-left:1px solid var(--line);transform:translateX(102%);transition:transform 200ms cubic-bezier(.2,.7,.2,1);display:flex;flex-direction:column;z-index:10}#ask.open{transform:none}
#ask .msgs{flex:1;overflow:auto;padding:10px 16px}
.m{display:grid;grid-template-columns:20px 1fr;gap:10px;padding:8px 0}.m svg{width:16px;height:16px;color:var(--t3);margin-top:2px}.m.agent svg{color:var(--agent)}.m .w{font-size:11px;color:var(--t3)}.m .t{color:var(--t1);line-height:1.5}
.prop{margin-top:8px;border-left:2px solid var(--agent);background:var(--b3);padding:10px 12px;border-radius:0 6px 6px 0;display:grid;gap:8px;font-size:12px}.prop b{font-weight:600}.prop i{font-style:normal;color:var(--agent)}
.bt{height:28px;padding:0 12px;border-radius:5px;font-size:12px;font-weight:600;display:inline-flex;align-items:center;gap:6px;background:var(--b4);color:var(--t1)}.bt:hover{background:#3a4340}.bt.acc{background:var(--acc);color:#1a1208}.bt.acc:hover{filter:brightness(1.08)}.bt.q{background:transparent;border:1px solid var(--line2);color:var(--t2)}.bt svg{width:14px;height:14px}
#ask .box{margin:10px 16px 14px;height:38px;display:flex;align-items:center;gap:8px;background:var(--b1);border:1px solid var(--line2);border-radius:6px;padding:0 6px 0 10px}#ask .box input{flex:1;background:none;border:0;outline:0}#ask .box svg{color:var(--t3)}
/* timeline */
#tl{grid-column:1/-1;grid-row:4}#tl .scroll{position:relative;overflow:auto;flex:1;background:var(--b1)}
.tracks{min-width:max-content;position:relative;padding:0 80px 20px 0}
.stages{display:grid;grid-template-columns:200px 1fr;height:24px;position:sticky;top:0;z-index:5;background:var(--b1)}.stages .lane{position:relative}
.stg{position:absolute;top:4px;height:16px;display:flex;align-items:center;padding:0 8px;font-size:10.5px;font-weight:600;color:var(--t1);border-radius:3px;background:var(--b3);border-left:3px solid var(--c)}
.track{display:grid;grid-template-columns:200px 1fr;height:60px;border-top:1px solid var(--line);position:relative}
.track .h{display:flex;align-items:center;gap:10px;padding:0 10px 0 14px;position:sticky;left:0;background:var(--b1);z-index:3;overflow:hidden;border-right:1px solid var(--line)}.track .h>div{flex:1;min-width:0}.track .h>svg{width:16px;height:16px;color:var(--c)}.track .h .n{font-weight:600;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.track .h .mm{font-size:11px;color:var(--t3);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.lane{position:relative;overflow-x:clip}.lane.hot{background:rgba(240,163,94,.06)}.beat{position:absolute;top:0;bottom:0;border-left:1px dashed var(--line)}
.region{position:absolute;top:6px;bottom:6px;border-radius:6px;background:color-mix(in srgb,var(--c) 10%,transparent);border:1px solid color-mix(in srgb,var(--c) 45%,transparent);pointer-events:none}.region .rt{position:absolute;left:8px;top:-9px;font-size:10px;font-weight:600;color:var(--c);background:var(--b1);padding:0 4px;pointer-events:auto;cursor:pointer}
.clip{position:absolute;top:14px;height:32px;display:flex;align-items:center;gap:8px;padding:0 12px 0 8px;background:var(--b3);border:1px solid var(--line2);border-left:3px solid var(--c);border-radius:5px;cursor:pointer;white-space:nowrap;user-select:none;font-size:12px}
.clip:hover{background:var(--b4)}.clip.sel{box-shadow:0 0 0 2px var(--acc);border-color:var(--acc)}.clip.multi{box-shadow:0 0 0 2px var(--acc)}.clip.gate{border-right:3px solid var(--agent)}.clip.outside{background:transparent;border-style:dashed;border-left-style:solid}
/* Two different things were both being drawn as hatching, and the board could not say which it meant.
   A sketch is a card with nothing in it yet — that is a blank, and a blank is best drawn empty:
   dashed outline, no fill. Hatching now means one thing only, and it is the more important one. */
.clip.draft{background:transparent;border-style:dashed;color:var(--t2)}.clip.draft .t{font-weight:500;font-style:italic}
/* Hatching means staves made this up and the person has not agreed to it yet. It is filled in — the
   card is not empty — but whose account it is has not been settled, so the fill is not solid either. */
.clip.guess{background:repeating-linear-gradient(135deg,var(--b2) 0 6px,var(--b3) 6px 8px)}
.clip.guess:hover{background:repeating-linear-gradient(135deg,var(--b3) 0 6px,var(--b4) 6px 8px)}
.clip .by{width:11px;height:11px;flex:none;border-radius:3px;border:1px solid var(--line2);cursor:pointer;
  background:repeating-linear-gradient(135deg,var(--b2) 0 3px,var(--b4) 3px 6px)}
.clip .by:hover{box-shadow:0 0 0 2px var(--acc)}
/* A card that was not on the canvas a moment ago lands on it. Short, once, and never on a board
   that was already described — construction is worth watching while it happens and tedious to replay. */
@keyframes clip-in{from{opacity:0;transform:translateY(6px) scale(.985)}to{opacity:1;transform:none}}
.clip.arriving{animation:clip-in .34s cubic-bezier(.2,.7,.3,1) both;animation-delay:var(--in,0ms)}
@media(prefers-reduced-motion:reduce){.clip.arriving{animation:none}}.clip.draft::after{content:'sketch';position:absolute;right:-1px;top:-9px;font-size:9px;font-style:normal;font-weight:600;letter-spacing:.02em;color:var(--t2);background:var(--b4);border:1px solid var(--line2);padding:0 5px;border-radius:3px}.clip.draft.sel::after{display:none}
.row.job.draft .n{font-style:italic;color:var(--t2)}.row.job.draft>svg.k{color:var(--t3)}
.clip>svg{width:13px;height:13px;color:var(--t2)}.clip .t{font-weight:600;max-width:260px;overflow:hidden;text-overflow:ellipsis}.clip .k{color:var(--t3);font-size:11px}.clip .tl{display:inline-flex;gap:2px;margin-left:4px}.clip .tl .pg{width:6px;height:8px}
.clip .pin{position:absolute;top:-7px;right:-7px;min-width:16px;height:16px;padding:0 4px;background:var(--alert);color:#fff;font-size:10px;font-weight:700;display:grid;place-items:center;border-radius:8px}
.clip .qm{position:absolute;top:-7px;left:-7px;width:16px;height:16px;background:var(--b4);border:1px solid var(--line2);color:var(--t1);font-size:10px;font-weight:800;display:grid;place-items:center;border-radius:8px}
.clip .port{position:absolute;right:-6px;top:50%;width:10px;height:10px;margin-top:-5px;border-radius:50%;background:var(--b1);border:1px solid var(--t2);opacity:0;cursor:crosshair}.clip:hover .port{opacity:1}
.dim .clip:not(.sel):not(.near):not(.multi){opacity:.35}
svg.wires{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible}.w{fill:none;stroke:#5a6561;stroke-width:1.4}.w.pull{stroke-dasharray:4 4}.w.admit{stroke:var(--agent);stroke-width:1.8}.w.near{stroke:var(--acc);stroke-width:1.8}.dim .w:not(.near){opacity:.3}
.marq{position:absolute;border:1px solid var(--acc);background:var(--accbg);pointer-events:none;z-index:4}
#selbar{position:absolute;z-index:8;display:none;gap:2px;background:var(--b3);border:1px solid var(--line2);border-radius:7px;padding:3px;box-shadow:0 10px 30px rgba(0,0,0,.4)}#selbar.show{display:flex}#selbar button{height:28px;padding:0 10px;border-radius:5px;display:inline-flex;align-items:center;gap:6px;font-size:12px;color:var(--t1)}#selbar button:hover{background:var(--b4)}#selbar button svg{width:14px;height:14px;color:var(--t2)}#selbar .sp{width:1px;background:var(--line2);margin:4px 3px}
.drop-row{height:36px;border-top:1px dashed var(--line2);display:grid;grid-template-columns:200px 1fr;color:var(--t3);font-size:11.5px}.drop-row .h{display:flex;align-items:center;gap:8px;padding-left:14px}
/* popover / sheets */
.pop{position:fixed;z-index:60;background:var(--b2);border:1px solid var(--line2);border-radius:8px;box-shadow:0 14px 40px rgba(0,0,0,.5);padding:4px;min-width:200px;display:none}.pop.show{display:block}.pop button{display:flex;gap:10px;align-items:center;width:100%;text-align:left;padding:8px 10px;border-radius:5px;font-size:12.5px;color:var(--t1)}.pop button:hover{background:var(--b3)}.pop button svg{width:14px;height:14px;color:var(--t2)}.pop hr{border:0;border-top:1px solid var(--line);margin:4px 6px}
.pop .settle{max-width:340px}.pop .settle>b{display:block;padding:8px 10px 2px;font-size:11px;font-weight:700;letter-spacing:.07em;text-transform:uppercase;color:var(--t2)}
.pop .settle>span{display:block;padding:0 10px 8px;font-size:12px;line-height:1.5;color:var(--t2)}
.pop .settle button span{white-space:normal;line-height:1.4}
.pop .sw{display:flex;gap:6px;padding:8px 10px}.pop .sw i{width:18px;height:18px;border-radius:50%;cursor:pointer;border:2px solid transparent}.pop .sw i:hover{border-color:#fff}
#veil{position:fixed;inset:0;background:rgba(0,0,0,.55);backdrop-filter:blur(4px);display:none;place-items:center;z-index:80}#veil.show{display:grid}
.sheet{width:520px;background:var(--b2);border:1px solid var(--line2);border-radius:10px;box-shadow:0 30px 80px rgba(0,0,0,.6)}.sheet .sh{padding:20px 24px 0;display:flex;align-items:center;gap:10px;font-weight:700;font-size:15px}.sheet .sh svg{width:18px;height:18px;color:var(--acc)}.sheet .sb{padding:14px 24px 4px}.sheet .sf{padding:10px 24px 20px;display:flex;justify-content:flex-end;gap:8px}
.fl{margin:0 0 14px}.fl label{display:block;font-size:12px;font-weight:600;margin-bottom:4px}.fl .hint{font-size:11.5px;color:var(--t3);margin:0 0 6px}.fl input,.fl textarea{width:100%;padding:9px 11px;background:var(--b1);border:1px solid var(--line2);border-radius:6px;color:var(--t1)}.fl input:focus,.fl textarea:focus{outline:0;border-color:var(--acc)}.fl textarea{min-height:64px;resize:vertical}
.fl .opts{display:flex;gap:6px;flex-wrap:wrap}.fl .opt{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border:1px solid var(--line2);border-radius:6px;cursor:pointer;font-size:12px;color:var(--t2)}.fl .opt:hover{color:var(--t1);border-color:var(--t3)}.fl .opt.on{background:var(--acc);color:#1a1208;border-color:var(--acc)}.fl .opt svg{width:13px;height:13px}
#toast{position:fixed;left:50%;bottom:20px;transform:translateX(-50%);background:#000;color:#fff;padding:8px 12px;border-radius:6px;font-size:12px;display:none;z-index:90}
</style></head><body>
<div id="ws">
 <header id="top">
  <span class="logo"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16M4 12h16M4 17h16"/><circle cx="9" cy="7" r="2" fill="currentColor"/><circle cx="15" cy="12" r="2" fill="currentColor"/><circle cx="11" cy="17" r="2" fill="currentColor"/></svg></span>
  <button class="name">How a claim becomes a decision <i class="ph ph-caret-down"></i></button>
  <span class="rec on" data-tip="Claude Code · connected · described 42 files, 2 min ago · stale check on"></span>
  <span class="grow"></span>
  <span class="meter" data-tip="people's hours a week"><i class="ph ph-user"></i><b>6.4</b></span>
  <span class="meter" data-tip="agent hours a week"><i class="ph ph-robot"></i><b>0</b></span>
  <span class="meter" data-tip="loose ends"><i class="ph ph-warning"></i><b id="loose">4</b></span><span class="meter" data-tip="sketches — jobs not yet filled in"><i class="ph ph-pencil-line"></i><b id="drafts">0</b></span>
  <button class="ib" style="position:relative" data-tip="needs you" onclick="toggleNeed()"><i class="ph ph-hand-pointing"></i><span class="badge" id="needn">3</span></button>
  <button class="ib" data-tip="interview" onclick="toast('Interview opens full-screen')"><i class="ph ph-microphone"></i></button>
  <span class="seg" id="views"><button class="ib on" data-v="normal" data-tip="the work"><i class="ph ph-rows"></i></button><button class="ib" data-v="chairs" data-tip="who could do this"><i class="ph ph-chair"></i></button><button class="ib" data-v="compare" data-tip="compare"><i class="ph ph-columns"></i></button><button class="ib" data-v="present" data-tip="present"><i class="ph ph-eye"></i></button></span>
  <button class="ib" data-tip="undo ⌘Z" onclick="undo()"><i class="ph ph-arrow-counter-clockwise"></i></button>
  <button class="ib" data-tip="share"><i class="ph ph-share-network"></i></button>
  <button class="ib" data-tip="export"><i class="ph ph-export"></i></button>
 </header>
 <section class="panel" id="ol"><div class="ph"><i class="ph ph-list-dashes"></i>Outline<span class="grow"></span><button class="ib" data-tip="add" onclick="addMenu(event,null)"><i class="ph ph-plus"></i></button><button class="ib" data-tip="collapse all" onclick="toggleAll()"><i class="ph ph-arrows-out-simple"></i></button></div><div class="body" id="olbody"></div></section>
 <div class="gutter"></div>
 <section class="panel" id="stage"><div class="ph"><i class="ph ph-rectangle"></i><span id="stt">Job</span><span class="grow"></span><button class="ib" id="askb" style="position:relative" data-tip="ask the system" onclick="toggleAsk()"><i class="ph ph-question"></i><span class="badge" id="askn">1</span></button><button class="ib" data-tip="focus on this job (Enter)" onclick="sel&&enterFocus(sel)"><i class="ph ph-arrows-in-simple"></i></button><button class="ib" data-tip="edit" onclick="sel&&sheetJob(job(sel))"><i class="ph ph-pencil-simple"></i></button></div><div class="sh" id="sh"></div><div class="body" id="sb"></div>
  <aside id="ask"><div class="ph"><i class="ph ph-question"></i>Ask the system<span class="grow"></span><button class="ib" onclick="toggleAsk(false)"><i class="ph ph-x"></i></button></div><div class="msgs" id="msgs"></div><div class="box"><i class="ph ph-microphone"></i><input id="askin" placeholder="Ask, answer, or change something…"><button class="ib" data-tip="commands"><i class="ph ph-lightning"></i></button></div></aside>
 </section>
 <div class="gutter" style="grid-column:1/-1"></div>
 <section class="panel" id="tl"><div id="fb"><i class="ph ph-arrows-in-simple"></i>Focused on <b id="fbn"></b> — what comes in and goes out is at the edges<span class="grow"></span><button onclick="leaveFocus()"><i class="ph ph-arrow-u-up-left"></i>back to the whole board</button></div><div class="ph"><i class="ph ph-rows"></i>Timeline<span class="grow"></span><span class="seg"><button class="ib" data-tip="zoom out" onclick="zoom(-1)"><i class="ph ph-minus"></i></button><button class="ib" data-tip="fit" onclick="fit()"><i class="ph ph-arrows-out-simple"></i></button><button class="ib" data-tip="zoom in" onclick="zoom(1)"><i class="ph ph-plus"></i></button></span></div><div class="scroll" id="tls"><div class="tracks" id="tracks"></div><div id="selbar"></div></div></section>
</div>
<div id="rv"><div class="wrap">
 <div class="eyebrow"><i class="ph ph-robot"></i>Described from claims-engine · 42 files read · 2 min ago</div>
 <h1>How a claim becomes a decision</h1>
 <p class="lead">Every claim gets a decision; no payout goes out that a person or a rule did not admit. 10 jobs across 2 people, 2 agents and 3 systems. 7 of them are the agent's description, not yet anyone's word.</p>
 <div class="mini" id="mini"></div>
 <div class="facts"><div class="fact"><i class="ph ph-globe-simple"></i><div><b>the claimant</b><br><span>who this is for</span></div></div><div class="fact"><i class="ph ph-user"></i><div><b>6.4</b><br><span>people's hours a week</span></div></div><div class="fact"><i class="ph ph-robot"></i><div><b>2</b><br><span>agents, 1 with instructions</span></div></div><div class="fact"><i class="ph ph-warning"></i><div><b>4</b><br><span>loose ends</span></div></div><div class="fact"><i class="ph ph-scales"></i><div><b>2</b><br><span>decisions nobody owns</span></div></div></div>
 <div class="sec surprise"><div><h3><i class="ph ph-hand-pointing"></i>Where a person would be surprised</h3><div class="why">the work does something nobody stands behind</div></div><div>
  <div class="item" onclick="openBoard('admit')"><span class="n">Admit the claim</span><span class="d">"timed out" goes nowhere — the claimant never hears</span><span class="go">open <i class="ph ph-caret-right"></i></span></div>
  <div class="item" onclick="openBoard('pay')"><span class="n">Pay or decline</span><span class="d">a rule decides "not already paid"; nobody owns the rule</span><span class="go">open <i class="ph ph-caret-right"></i></span></div></div></div>
 <div class="sec blind"><div><h3><i class="ph ph-warning"></i>Where an agent is trusted blind</h3><div class="why">nobody has said what the tool returns or what would tell you it went wrong</div></div><div>
  <div class="item" onclick="openBoard('triage')"><span class="n">Sort the claim</span><span class="d">reads the first message only · labels checked by no one</span><span class="go">open <i class="ph ph-caret-right"></i></span></div>
  <div class="item" onclick="openBoard('assess')"><span class="n">Assess the claim</span><span class="d">Policy PDF: the cover table, not the exclusions · checks nothing</span><span class="go">open <i class="ph ph-caret-right"></i></span></div></div></div>
 <div class="sec words"><div><h3><i class="ph ph-translate"></i>Not yet in the adjuster's words</h3><div class="why">names from the system, jobs without an outcome</div></div><div>
  <div class="item"><span class="n">3 jobs</span><span class="d">"Drain the queue", "Run the scorer", "Sync the ledger"</span><span class="go">rename <i class="ph ph-caret-right"></i></span></div></div></div>
 <div class="sec first"><div><h3><i class="ph ph-check"></i>Three things to do first</h3></div><div>
  <div class="item"><span class="n">1</span><span class="d">Say where "timed out" goes — or that it stops, and who tells the claimant</span></div>
  <div class="item"><span class="n">2</span><span class="d">Name who owns the payout rule</span></div>
  <div class="item"><span class="n">3</span><span class="d">Ask the agent to break "Sort the claim" down and say what the inbox actually returns</span></div></div></div>
 <div class="cta"><button class="bt acc" style="height:36px;padding:0 16px" onclick="openBoard('admit')"><i class="ph ph-rows"></i>Open the board</button><button class="bt q" style="height:36px" onclick="toast('Shared')"><i class="ph ph-share-network"></i>Share this review</button><span class="hint">staves.io/b/7f3a…/review</span></div>
</div></div>
<div class="pop" id="pop"></div><div id="veil"></div><div id="toast"></div>
<script>
const ICONS=''' + icons + r''';
function icons(){ document.querySelectorAll('i.ph').forEach(el=>{ const name=[...el.classList].find(c=>c.startsWith('ph-')); const k=name?name.slice(3):''; const p=ICONS[k]||ICONS['rectangle']; const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'); svg.setAttribute('viewBox','0 0 256 256'); svg.setAttribute('class','ic'); svg.innerHTML=p; if(el.hasAttribute('style')) svg.setAttribute('style',el.getAttribute('style')); [...el.classList].filter(c=>!c.startsWith('ph')).forEach(c=>svg.classList.add(c)); el.replaceWith(svg); }); }
new MutationObserver(()=>icons()).observe(document.documentElement,{childList:true,subtree:true});
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
/* ===== data ===== */
const WHOI={person:'ph-user',team:'ph-users',agent:'ph-robot',system:'ph-database',outside:'ph-globe-simple',build:'ph-hammer'};
const WHOC={person:'var(--person)',team:'var(--person)',agent:'var(--agent)',system:'var(--system)',outside:'var(--outside)',build:'var(--system)'};
const TRIG={hand:['ph-hand-pointing','when someone gets to it'],arrive:['ph-tray-arrow-down','when something arrives'],chain:['ph-link','when the previous one ends'],clock:['ph-clock','on a schedule']};
const KIND={look:'look something up',read:'read and pull out',match:'match two things',draft:'draft from sources',decide:'decide',tell:'tell someone',move:'move between tools',wait:'wait for someone'};
const KI=k=>({decide:'ph-scales',wait:'ph-hourglass',tell:'ph-paper-plane-tilt',read:'ph-file-text',look:'ph-magnifying-glass',match:'ph-arrows-left-right',draft:'ph-pencil-line'})[k]||'ph-arrow-right';
let TRACKS=[{id:'claimant',k:'outside',n:'Claimant',m:'who this is for',who:true},{id:'anna',k:'person',n:'Anna · adjuster',m:'two people share a queue'},{id:'agent',k:'agent',n:'An agent',m:'not yet built'},{id:'sys',k:'build',n:'To be built',m:'what nothing does yet'}];
let JOBS=[
 {id:'file',t:'claimant',c:0,n:'Files a claim',out:true,trig:'hand',o:'A claim is in our hands with a policy number and a story.',for:'the claimant',tasks:[]},
 {id:'admit',t:'anna',c:1,n:'Admit the claim',trig:'arrive',gate:{rule:'no claim without a policy number',who:'Anna'},o:'A claim we can work on exists, or the claimant knows why not.',for:'the claimant',d:'the claim row exists, or a letter is queued',q:'What do you do when the policy number doesn\'t match anything?',issues:[{t:'Why does the duplicate check only look at one month?',st:'answered',by:'Claude Code',a:'The check calls listClaims({since:30d}) — a default nobody set on purpose. Reading a year costs ~40 ms. Proposed below.',prop:true},{t:'The wait has no bound — what ends it?',st:'raised'}],
  tasks:[{id:'t1',n:'Find the policy',k:'look',tools:[{n:'Policy desk',cov:.9}],qt:'"Policy desk, type the number. If it isn\'t there I try the name — half the time the number is wrong."'},{id:'t2',n:'Wait for the claimant',k:'wait',tools:[],w:'no bound on the wait'},{id:'t3',n:'Check it is not a duplicate',k:'match',tools:[{n:'Claims list',cov:.4}],w:'reads a month of what it claims to check'},{id:'t4',n:'Decide if it is ours',k:'decide',tools:[]}]},
 {id:'assess',t:'anna',c:2,n:'Assess the claim',trig:'chain',o:'An assessment exists with evidence and a recommendation.',for:'me, before I decide',issues:[{t:'Score against the policy reads the cover table only — is that enough?',st:'proposed'}],tasks:[{id:'t5',n:'Gather the evidence',k:'read',tools:[{n:'Insurer portal',cov:.3},{n:'Registry',cov:1}]},{id:'t6',n:'Score against the policy',k:'match',tools:[{n:'Policy PDF',cov:.2}],w:'checks nothing'},{id:'t7',n:'Write the recommendation',k:'draft',tools:[]}]},
 {id:'decide',t:'anna',c:4,n:'Decide the claim',trig:'hand',gate:{rule:'a person decides above €5k',who:'Anna'},o:'A decision the company stands behind.',for:'the claimant',d:'decision recorded with a reason',conf:true,tasks:[{id:'t8',n:'Read the recommendation',k:'read',tools:[]},{id:'t9',n:'Decide',k:'decide',tools:[]}]},
 {id:'pay',t:'sys',c:5,n:'Pay or decline',trig:'chain',o:'The claimant has the money or the letter.',for:'the claimant',tasks:[{id:'t10',n:'Send the money',k:'tell',tools:[]},{id:'t11',n:'Send the letter',k:'tell',tools:[]}]},
 {id:'triage',t:'agent',c:3,n:'Sort the claim',trig:'chain',o:'The claim is labelled simple or complex, with a reason.',for:'the adjuster',instr:{path:'src/prompts/triage.md',sum:'label simple or complex from the first message only; never decide',text:'# Triage agent\n\nYou label incoming claims.\nRead the first message only.\nIf it mentions a payment, label billing.\nIf it names an error code, label technical.\nOtherwise label general.\nWhen unsure, label general and say so.\n\nNever approve. Never decline. A person decides.'},tasks:[{id:'t12',n:'Read the first message',k:'read',tools:[{n:'Claims inbox',cov:.2}],w:'reads the first message only'},{id:'t13',n:'Label it',k:'match',tools:[]}]},
 {id:'receive',t:'claimant',c:6,n:'Receives the outcome',out:true,o:'The claimant has the money, or the letter.',for:'the claimant',tasks:[]},
];
let WIRES=[['file','admit','pull'],['admit','triage',''],['triage','assess','admit'],['assess','decide','pull'],['decide','pay','admit'],['pay','receive','']];
let REGIONS=[{id:'r1',n:'Intake',c:'#f0a35e',members:['file','admit']},{id:'r2',n:'Assessment',c:'#4fcb92',members:['assess']},{id:'r3',n:'Decision',c:'#8fa3b8',members:['decide']},{id:'r4',n:'Payout',c:'#d9c9a6',members:['pay','receive']}];
const SW=['#f0a35e','#4fcb92','#8fa3b8','#d9c9a6','#e07a7a','#b48ce0'];
const CONV={admit:[{w:'the interviewer',k:'agent',t:'What do you do when the policy number doesn\'t match anything?'},{w:'the system',k:'agent',t:'The duplicate check reads one month of the claims list. Anything older passes. Make it read a year and add a check that stops when the list is unavailable?',prop:'<b>Check it is not a duplicate</b> — reads 12 months, not 1 · adds a check: <i>list reachable, else stop and tell Anna</i>'}]};
let sel=null,selKind='job',multi=new Set(),opened=new Set(['anna','admit']),zoomv=1,view='normal',needOnly=false,hist=[];
const track=id=>TRACKS.find(t=>t.id===id),job=id=>JOBS.find(j=>j.id===id);
const findTask=id=>{for(const j of JOBS){const t=(j.tasks||[]).find(x=>x.id===id);if(t)return{j,t};}return null;};
const isDraft=j=>!j.out&&!j.sys&&!(j.o&&j.for);
const findings=j=>{const f=[];(j.tasks||[]).forEach(t=>{if(t.w)f.push(t.w);});if(j.q)f.push('a question waits');return f;};
function snap(){ hist.push(JSON.stringify({TRACKS,JOBS,WIRES,REGIONS})); if(hist.length>50) hist.shift(); }
function undo(){ const s=hist.pop(); if(!s){toast('Nothing to undo');return;} ({TRACKS,JOBS,WIRES,REGIONS}=JSON.parse(s)); render(); toast('Undone'); }
/* ===== outline ===== */
function outline(){ const B=$('#olbody'); let h='';
  TRACKS.forEach(t=>{ const jobs=JOBS.filter(j=>j.t===t.id); const isOpen=opened.has(t.id); h+='<div class="row who '+t.k+' '+(isOpen?'open':'')+(sel===t.id?' sel':'')+'" style="--ind:8px" data-id="'+t.id+'" data-kind="who" draggable="true"><span class="tw"><i class="ph ph-caret-right"></i></span><i class="ph '+WHOI[t.k]+' k"></i><span class="n">'+t.n+'</span><span class="m">'+jobs.length+'</span><button class="add" onclick="event.stopPropagation();addMenu(event,\''+t.id+'\')"><i class="ph ph-plus"></i></button></div>';
    if(isOpen) jobs.forEach(j=>{ const jo=opened.has(j.id); const F=findings(j); h+='<div class="row job '+(isDraft(j)?'draft ':'')+(jo?'open':'')+(sel===j.id?' sel':'')+(multi.has(j.id)?' sel':'')+'" style="--ind:26px" data-id="'+j.id+'" data-kind="job" draggable="true"><span class="tw">'+((j.tasks||[]).length?'<i class="ph ph-caret-right"></i>':'')+'</span><i class="ph '+(j.trig?TRIG[j.trig][0]:'ph-rectangle')+' k"></i><span class="n">'+j.n+'</span><span class="m">'+(j.q?'<span class="q">?</span>':'')+(F.length?'<span class="cnt">'+F.length+'</span>':'')+(j.gate?'<i class="ph ph-scales"></i>':'')+'</span><button class="add" onclick="event.stopPropagation();addMenu(event,\''+j.id+'\')"><i class="ph ph-plus"></i></button></div>';
      if(jo) (j.tasks||[]).forEach(x=>{ h+='<div class="row task'+(sel===x.id?' sel':'')+(multi.has(x.id)?' sel':'')+'" style="--ind:46px" data-id="'+x.id+'" data-kind="task" draggable="true"><span class="tw"></span><i class="ph '+KI(x.k)+' k"></i><span class="n">'+x.n+'</span><span class="m">'+(x.tools||[]).map(tl=>'<span class="pg" style="--cov:'+Math.round((tl.cov||0)*100)+'%"></span>').join('')+(x.w?'<span class="cnt">1</span>':'')+'</span></div>'; }); }); });
  B.innerHTML=h;
  $$('.row',B).forEach(r=>{ r.onclick=e=>{ const id=r.dataset.id,k=r.dataset.kind; if(e.target.closest('.tw')&&k!=='task'){ opened.has(id)?opened.delete(id):opened.add(id); outline(); return; } if(e.shiftKey){ multi.has(id)?multi.delete(id):multi.add(id); render(); return; } multi.clear(); select(id,k); };
    r.ondblclick=()=>{ const id=r.dataset.id; if(r.dataset.kind!=='task'){ opened.has(id)?opened.delete(id):opened.add(id); outline(); } };
    r.ondragstart=e=>{ e.dataTransfer.setData('text/plain',r.dataset.kind+':'+r.dataset.id); e.dataTransfer.effectAllowed='move'; };
    r.ondragover=e=>{ e.preventDefault(); const rr=r.getBoundingClientRect(); const after=e.clientY>rr.top+rr.height*.6; r.classList.toggle('drag-after',after); r.classList.toggle('drag-over',!after); };
    r.ondragleave=()=>{ r.classList.remove('drag-over','drag-after'); };
    r.ondrop=e=>{ e.preventDefault(); const after=r.classList.contains('drag-after'); r.classList.remove('drag-over','drag-after'); const [k,id]=e.dataTransfer.getData('text/plain').split(':'); dropOutline(k,id,r.dataset.kind,r.dataset.id,after); }; }); }
function dropOutline(k,id,tk,tid,after){ if(id===tid) return; snap();
  if(k==='task'){ const src=findTask(id); if(!src) return; let dest=null,idx=null;
    if(tk==='task'){ const d=findTask(tid); dest=d.j; idx=d.j.tasks.indexOf(d.t)+(after?1:0); }
    else if(tk==='job'){ dest=job(tid); idx=after?dest.tasks.length:0; }
    else if(tk==='who'){ // task onto a person: becomes a new job for them
      const nt=track(tid); const nj={id:'j'+Date.now(),t:tid,c:Math.max(...JOBS.map(j=>j.c))+1,n:src.t.n,trig:nt.k==='person'?'hand':'chain',tasks:[]}; JOBS.push(nj); dest=nj; idx=0; toast('New job for '+nt.n+' — name it'); }
    if(!dest) return;
    if(dest!==src.j && track(dest.t).k==='agent' && src.t.k==='decide'){ toast('A decision can\'t move to an agent — keep it with a person'); hist.pop(); return; }
    if(dest!==src.j && track(dest.t).k==='agent' && (src.t.tools||[]).some(t=>t.reach==='screen')){ toast('This task uses a tool an agent can\'t reach'); }
    src.j.tasks=src.j.tasks.filter(x=>x!==src.t); if(dest===src.j&&idx>src.j.tasks.length) idx=src.j.tasks.length; dest.tasks.splice(idx,0,src.t); opened.add(dest.id); opened.add(dest.t); render(); return; }
  if(k==='job'){ const j=job(id); if(tk==='who'){ if(j.t!==tid){ j.t=tid; toast('Moved to '+track(tid).n+' — handover checks apply'); } }
    else if(tk==='job'){ const d=job(tid); if(d.t!==j.t){ j.t=d.t; } // reorder among jobs by column
      const sibs=JOBS.filter(x=>x.t===d.t&&x.id!==id).sort((a,b)=>a.c-b.c); const di=sibs.indexOf(d)+(after?1:0); sibs.splice(di,0,j); sibs.forEach((x,i)=>x.c=Math.min(...JOBS.filter(y=>y.t===d.t).map(y=>y.c))+i); }
    else if(tk==='task'){ const d=findTask(tid); // job dropped into a job: becomes tasks of it
      d.j.tasks.push(...(j.tasks.length?j.tasks:[{id:'t'+Date.now(),n:j.n,k:'look',tools:[]}])); JOBS=JOBS.filter(x=>x.id!==id); WIRES=WIRES.filter(w=>w[0]!==id&&w[1]!==id); }
    render(); }
}
function toggleAll(){ if(opened.size){ opened.clear(); } else { TRACKS.forEach(t=>opened.add(t.id)); JOBS.forEach(j=>opened.add(j.id)); } outline(); }
function addMenu(e,pid){ const p=$('#pop'); const isTrack=pid&&track(pid); const isJob=pid&&job(pid);
  const items=isJob?[['task','ph-squares-four','a task'],['decision','ph-scales','a decision'],['wait','ph-hourglass','a wait'],['tool','ph-wrench','a tool'],['check','ph-check-square','a check'],['case','ph-briefcase','a case']]:isTrack?[['job','ph-rectangle','a job'],['region','ph-bookmark-simple','a region']]:[['person','ph-user','a person'],['agent','ph-robot','an agent'],['system','ph-database','a system'],['outside','ph-globe-simple','outside'],['build','ph-hammer','to be built'],['—'],['pattern','ph-puzzle-piece','a pattern…']];
  p.innerHTML=items.map(([k,i,l])=>k==='—'?'<hr>':'<button onclick="addThing(\''+k+'\',\''+(pid||'')+'\')"><i class="ph '+i+'"></i>'+l+'</button>').join(''); p.style.left=Math.min(window.innerWidth-220,e.clientX)+'px'; p.style.top=e.clientY+'px'; p.classList.add('show'); e.stopPropagation(); }
function addThing(k,pid){ $('#pop').classList.remove('show'); snap();
  if(WHOI[k]){ const id='t'+Date.now(); TRACKS.push({id,k,n:{person:'Someone',agent:'An agent',system:'A system',outside:'Outside',build:'To be built'}[k],m:''}); opened.add(id); render(); sheet('Who is this?',[['n','Name or role','',TRACKS.at(-1).n],['m','One line','what they are for']],v=>{Object.assign(TRACKS.at(-1),{n:v.n||TRACKS.at(-1).n,m:v.m});render();},WHOI[k]); return; }
  if(k==='job'){ const id='j'+Date.now(); const t=track(pid); JOBS.push({id,t:pid,c:Math.max(0,...JOBS.map(j=>j.c))+1,n:'New job',trig:t.k==='person'?'hand':'chain',tasks:[]}); opened.add(pid); render(); select(id,'job'); sheetJob(job(id)); return; }
  if(k==='task'){ const j=job(pid); const t={id:'t'+Date.now(),n:'New task',k:'look',tools:[]}; j.tasks.push(t); opened.add(pid); render(); select(t.id,'task'); sheetTask(j,t); return; }
  if(k==='decision'){ sheetGate(job(pid)); return; }
  if(k==='region'){ sheetRegion(null,[pid]); return; }
  toast('Added '+k); }
/* ===== selection & stage ===== */
function select(id,k){ sel=id; selKind=k; if(k==='task'){ const f=findTask(id); if(f){ opened.add(f.j.t); opened.add(f.j.id);} } if(k==='job'){ opened.add(job(id).t); } render(); }
function render(){ outline(); timeline(); stage(); $('#loose').textContent=JOBS.reduce((a,j)=>a+findings(j).length,0); $('#needn').textContent=JOBS.filter(j=>findings(j).length).length; $('#drafts').textContent=JOBS.filter(isDraft).length; }
function stage(){ const H=$('#sh'),B=$('#sb'); let j=null,t=null; if(selKind==='task'){ const f=findTask(sel); if(f){j=f.j;t=f.t;} } else if(selKind==='job') j=job(sel);
  if(!j){ const tr=sel?track(sel):null; $('#stt').textContent=tr?tr.n:'Board'; H.innerHTML='<div><div class="crumb">the board</div><h2><i class="ph '+(tr?WHOI[tr.k]:'ph-scroll')+'"></i>'+(tr?tr.n:'How a claim becomes a decision')+'</h2><div class="sub">'+(tr?tr.m:'Every claim gets a decision; no payout goes out that a person or a rule did not admit.')+'</div><div class="chips"><span class="chip"><i class="ph ph-users"></i><b>'+TRACKS.length+'</b></span><span class="chip"><i class="ph ph-rectangle"></i><b>'+JOBS.length+'</b></span><span class="chip alert"><i class="ph ph-warning"></i><b>'+JOBS.reduce((a,x)=>a+findings(x).length,0)+'</b></span></div></div>'; B.innerHTML=''; msgs('board'); return; }
  $('#stt').textContent=t?'Task':'Job'; const tr=track(j.t); const F=findings(j);
  H.innerHTML='<div><div class="crumb"><b onclick="select(null,\'board\')">the board</b><i class="ph ph-caret-right"></i><b onclick="select(\''+tr.id+'\',\'who\')">'+tr.n+'</b>'+(t?'<i class="ph ph-caret-right"></i><b onclick="select(\''+j.id+'\',\'job\')">'+j.n+'</b>':'')+'</div><h2><i class="ph '+(t?KI(t.k):(j.trig?TRIG[j.trig][0]:'ph-rectangle'))+'"></i>'+(t?t.n:j.n)+(j.gate&&!t?'<i class="ph ph-scales" style="color:var(--agent)"></i>':'')+'</h2>'+(t?'<div class="sub">'+(KIND[t.k]||t.k)+(t.qt?' · '+t.qt:'')+'</div>':(j.o?'<div class="sub">'+j.o+'</div>':'<div class="sub q" onclick="sheetJob(job(\''+j.id+'\'))">what is different when it\'s done?</div>'))
   +'<div class="chips">'+(!t&&isDraft(j)?'<span class="chip" style="background:var(--accbg);color:var(--acc);border-color:transparent" onclick="sheetJob(job(\''+j.id+'\'))"><i class="ph ph-pencil-line" style="color:var(--acc)"></i>sketch — say what a person gets to make it real</span>':'')+(t?(t.tools||[]).map(tl=>'<span class="chip"><span class="pg" style="--cov:'+Math.round((tl.cov||0)*100)+'%"></span>'+tl.n+'</span>').join('')+(t.w?'<span class="chip alert"><i class="ph ph-warning"></i>'+t.w+'</span>':''):(j.for?'<span class="chip" onclick="sheetJob(job(\''+j.id+'\'))"><i class="ph ph-user"></i><b>'+j.for+'</b></span>':'<span class="chip q"><i class="ph ph-user"></i>who?</span>')+(j.d?'<span class="chip" onclick="sheetJob(job(\''+j.id+'\'))"><i class="ph ph-check-square"></i>'+j.d+'</span>':'<span class="chip q"><i class="ph ph-check-square"></i>done when?</span>')+(j.gate?'<span class="chip" onclick="sheetGate(job(\''+j.id+'\'))"><i class="ph ph-scales"></i><b>'+j.gate.who+'</b> decides</span>':'')+(F.length?'<span class="chip alert" onclick="toggleAsk(true)"><i class="ph ph-warning"></i><b>'+F.length+'</b></span>':''))+'</div></div><div class="right"><div class="rowb"><span class="chip"><i class="ph '+(j.trig?TRIG[j.trig][0]:'ph-play')+'"></i>'+(j.trig?TRIG[j.trig][1]:'')+'</span></div></div>';
  if(t){ B.innerHTML='<div class="acct"><div class="f"><label>What you open, how far, when you stop</label><div class="v '+(t.how?'':'q')+'" onclick="sheetTask(job(\''+j.id+'\'),findTask(\''+t.id+'\').t)">'+(t.how||'say it as you would to a new colleague')+'</div></div><div class="f"><label>What must be true when it\'s done</label><div class="v '+(t.chk?'':'q')+'" onclick="sheetTask(job(\''+j.id+'\'),findTask(\''+t.id+'\').t)">'+(t.chk||'a check, and what happens when it fails')+'</div></div></div>'; msgs(j.id); return; }
  const cards=(j.tasks||[]).map((x,i,a)=>'<div class="card'+(multi.has(x.id)?' sel':'')+'" data-t="'+x.id+'" draggable="true" onclick="event.shiftKey?(multi.has(\''+x.id+'\')?multi.delete(\''+x.id+'\'):multi.add(\''+x.id+'\'),render()):select(\''+x.id+'\',\'task\')"><div class="big"><i class="ph '+KI(x.k)+'"></i></div><div class="h">'+x.n+'</div><div class="k">'+(KIND[x.k]||x.k)+'</div><div class="tools">'+(x.tools||[]).map(tl=>'<span class="tool"><span class="pg" style="--cov:'+Math.round((tl.cov||0)*100)+'%"></span>'+tl.n+'</span>').join('')+'</div>'+(x.w?'<div class="w"><i class="ph ph-warning"></i>'+x.w+'</div>':'')+'<div class="foot"><i class="ph ph-arrows-out-simple"></i>open</div></div>'+(i<a.length-1?'<div class="splitter" data-tip="split here" onclick="splitAt(\''+j.id+'\','+(i+1)+')"><i class="ph ph-columns"></i></div>':'')).join('')+'<div class="card new" onclick="addThing(\'task\',\''+j.id+'\')"><i class="ph ph-plus" style="width:20px;height:20px"></i></div>';
  const issues=(j.issues||[]).map(x=>'<div class="iss '+x.st.replace(' ','-')+'"><i class="ph '+(x.st==='raised'?'ph-hand-pointing':x.st==='picked up'?'ph-robot':x.st==='answered'?'ph-check':'ph-git-diff')+'"></i><div class="t"><div>'+x.t+'</div>'+(x.a?'<div class="ans"><i class="ph ph-robot"></i><span><b>'+x.by+'</b> · '+x.a+'</span></div>':'')+'</div><span class="st">'+x.st+'</span>'+(x.prop?'<button class="bt acc" style="height:24px" onclick="toggleAsk(true)"><i class="ph ph-git-diff"></i>Proposal</button>':'')+'</div>').join('')
   +'<div class="raise"><i class="ph ph-hand-pointing"></i><input placeholder="Raise something about this job — R" onkeydown="if(event.key===\'Enter\'&&this.value.trim()){(job(\''+j.id+'\').issues=job(\''+j.id+'\').issues||[]).unshift({t:this.value.trim(),st:\'raised\'});render();toast(\'Raised — the agent picks it up on /issues\');}"><span class="k">↵</span></div>';
  const instr=j.instr?'<div class="instr"><div class="ih"><i class="ph ph-list-checks"></i><b>Works from</b><span class="path">'+j.instr.path+'</span><span class="grow"></span><span class="ro"><i class="ph ph-eye"></i>read-only from the repo</span></div><div class="sum">'+j.instr.sum+'</div><pre>'+j.instr.text+'</pre></div>':'';
  B.innerHTML='<div class="chain">'+cards+'</div>'+'<div class="issues"><div class="ih"><i class="ph ph-hand-pointing"></i><b>Raised</b><span class="cnt">'+(j.issues||[]).filter(x=>x.st==='raised').length+' waiting · '+(j.issues||[]).filter(x=>x.st!=='raised').length+' with the agent</span><span class="grow"></span><button class="bt" style="height:24px" onclick="toast(\'Handed to Claude Code — /mcp__staves__issues\')"><i class="ph ph-robot"></i>Hand to the agent</button></div>'+issues+'</div>'+instr+(j.tasks&&j.tasks.length?'':'<div class="acct"><div class="f"><label>No tasks yet</label><div class="v q" onclick="addThing(\'task\',\''+j.id+'\')">break it down — or drag tasks here from the outline</div></div></div>');
  $$('.card[data-t]',B).forEach(c=>{ c.ondragstart=e=>e.dataTransfer.setData('text/plain','task:'+c.dataset.t); c.ondragover=e=>{e.preventDefault();c.style.borderColor='var(--acc)';}; c.ondragleave=()=>c.style.borderColor=''; c.ondrop=e=>{ e.preventDefault(); c.style.borderColor=''; const [k,id]=e.dataTransfer.getData('text/plain').split(':'); if(k==='task') dropOutline('task',id,'task',c.dataset.t,true); }; });
  msgs(j.id); }
function splitAt(jid,i){ const j=job(jid); const after=j.tasks.slice(i); const produces=after.some(x=>x.k==='tell'||x.k==='draft'||x.k==='decide'); if(!produces){ toast('Nothing changes hands here — this is still one job'); return; } snap(); const nj={id:'j'+Date.now(),t:j.t,c:j.c+1,n:after[0].n,trig:'chain',tasks:after}; j.tasks=j.tasks.slice(0,i); JOBS.filter(x=>x.t===j.t&&x.c>j.c).forEach(x=>x.c++); JOBS.push(nj); WIRES.push([j.id,nj.id,'']); opened.add(nj.id); render(); select(nj.id,'job'); sheetJob(nj); }
function msgs(key){ const M=$('#msgs'); const L=CONV[key]||[]; $('#askn').textContent=L.filter(m=>m.prop&&!m.done).length||''; $('#askn').style.display=L.some(m=>m.prop&&!m.done)?'grid':'none'; M.innerHTML=L.map((m,i)=>'<div class="m '+m.k+'"><i class="ph '+(m.k==='agent'?'ph-robot':'ph-user')+'"></i><div><div class="w">'+m.w+'</div><div class="t">'+m.t+'</div>'+(m.prop&&!m.done?'<div class="prop"><div>'+m.prop+'</div><div style="display:flex;gap:6px"><button class="bt acc" onclick="CONV[\''+key+'\']['+i+'].done=1;job(\'admit\').tasks[2].w=null;job(\'admit\').tasks[2].tools[0].cov=1;render()"><i class="ph ph-check"></i>Accept</button><button class="bt q" onclick="CONV[\''+key+'\']['+i+'].done=1;render()">Not this</button></div></div>':m.done?'<div class="w" style="color:var(--agent);margin-top:4px">done</div>':'')+'</div></div>').join('')||'<div class="m"><i class="ph ph-robot"></i><div><div class="w">the system</div><div class="t">Ask about this, or tell me what to change.</div></div></div>'; }
function toggleAsk(on){ const a=$('#ask'); a.classList.toggle('open',on==null?!a.classList.contains('open'):on); }
function toggleNeed(){ needOnly=!needOnly; timeline(); }
/* ===== context menus ===== */
let connectMode=null;
function ctx(e,items){ e.preventDefault(); e.stopPropagation(); const p=$('#pop'); p.innerHTML=items.map(it=>it==='—'?'<hr>':'<button onclick="$(\'#pop\').classList.remove(\'show\');('+it[2]+')()"><i class="ph '+it[1]+'"></i>'+it[0]+(it[3]?'<span style="margin-left:auto;color:var(--t3);font-size:11px">'+it[3]+'</span>':'')+'</button>').join(''); p.classList.add('show'); p.style.left=Math.min(window.innerWidth-p.offsetWidth-8,e.clientX)+'px'; p.style.top=Math.min(window.innerHeight-p.offsetHeight-8,e.clientY)+'px'; }
function colAt(e,lane){ const r=lane.getBoundingClientRect(); return Math.max(0,Math.round(((e.clientX-r.left)/zoomv-X0)/COL)); }
function addSketch(tid,c,k){ snap(); const t=track(tid); const id='j'+Date.now(); JOBS.push({id,t:tid,c,n:{job:'New job',wait:'Wait',queue:'A queue'}[k],trig:t.k==='person'?'hand':'chain',tasks:[],sk:k==='job'?undefined:k}); opened.add(tid); render(); select(id,'job'); if(k==='job') sheetJob(job(id)); }
function addTrackAt(i,k){ snap(); TRACKS.splice(i,0,{id:'t'+Date.now(),k,n:{person:'Someone',agent:'An agent',system:'A system',outside:'Outside'}[k],m:''}); render(); }
function laneMenu(e,t,lane){ const c=colAt(e,lane); const i=TRACKS.indexOf(t);
  ctx(e,[['A job here','ph-rectangle',`()=>addSketch('${t.id}',${c},'job')`,'J'],['A wait','ph-hourglass',`()=>addSketch('${t.id}',${c},'wait')`],['A queue','ph-list-dashes',`()=>addSketch('${t.id}',${c},'queue')`],['A region from the selection','ph-bookmark-simple','()=>groupRegion()'],'—',['Someone above','ph-user-plus',`()=>addTrackAt(${i},'person')`],['Someone below','ph-user-plus',`()=>addTrackAt(${i+1},'person')`],['An agent below','ph-robot',`()=>addTrackAt(${i+1},'agent')`],['A system below','ph-database',`()=>addTrackAt(${i+1},'system')`]]); }
function clipMenu(e,j){ ctx(e,[['Open','ph-arrows-out-simple',`()=>select('${j.id}','job')`,'↵'],['Focus','ph-arrows-in-simple',`()=>enterFocus('${j.id}')`],'—',['Add a task','ph-squares-four',`()=>addThing('task','${j.id}')`,'T'],['A decision here','ph-scales',`()=>sheetGate(job('${j.id}'))`,'G'],['A wait after','ph-hourglass',`()=>{snap();JOBS.push({id:'j'+Date.now(),t:'${j.t}',c:${j.c}+1,n:'Wait',trig:'chain',tasks:[],sk:'wait'});render();}`],['A way out','ph-arrow-bend-up-right',`()=>sheet('A way out',[['when','When?',''],['to','Where does it go?','']],v=>{snap();(job('${j.id}').exits=job('${j.id}').exits||[]).push(v);render();})`],'—',['Connect to…','ph-flow-arrow',`()=>{connectMode='${j.id}';toast('Click the job it hands to');}`,'A'],['Raise something','ph-hand-pointing',`()=>{select('${j.id}','job');setTimeout(()=>$('.raise input')?.focus(),50)}`,'R'],['Ask the agent','ph-robot',`()=>{select('${j.id}','job');toggleAsk(true)}`],'—',['Split into tasks','ph-columns',`()=>{select('${j.id}','job');toast('Click between two tasks to split')}`],['Delete','ph-x',`()=>{snap();JOBS=JOBS.filter(x=>x.id!=='${j.id}');WIRES=WIRES.filter(w=>w[0]!=='${j.id}'&&w[1]!=='${j.id}');selectNone()}`,'⌫']]); }
function selectNone(){ sel=null; multi.clear(); render(); }
/* ===== timeline ===== */
const COL=224,X0=20;
function timeline(){ const el=$('#tracks'); el.innerHTML=''; const ncol=Math.max(7,...JOBS.map(j=>j.c+1));
  const st=document.createElement('div'); st.className='stages'; st.innerHTML='<div></div><div class="lane"></div>'; el.appendChild(st);
  TRACKS.forEach(t=>{ const d=document.createElement('div'); d.className='track '+t.k; d.style.setProperty('--c',WHOC[t.k]); d.dataset.track=t.id; d.innerHTML='<div class="h"'+(t.who?' style="background:linear-gradient(90deg,rgba(143,163,184,.12),transparent)"':'')+'><i class="ph '+WHOI[t.k]+'"></i><div><div class="n">'+t.n+'</div><div class="mm">'+t.m+'</div></div></div><div class="lane"></div>'; const lane=d.querySelector('.lane'); for(let c=1;c<ncol;c++){const b=document.createElement('i');b.className='beat';b.style.left=(X0+c*COL-12)+'px';lane.appendChild(b);}
    JOBS.filter(j=>j.t===t.id).forEach(j=>{ const c=document.createElement('div'); c.className='clip'+(j.out?' outside':'')+(j.gate?' gate':'')+(sel===j.id?' sel':'')+(multi.has(j.id)?' multi':'')+(isDraft(j)?' draft':''); c.style.setProperty('--c',WHOC[t.k]); c.dataset.job=j.id; c.style.left=(X0+j.c*COL)+'px'; const tools=(j.tasks||[]).flatMap(x=>x.tools||[]); const F=findings(j);
      c.innerHTML=(j.sk==='wait'?'<i class="ph ph-hourglass" style="color:var(--acc)"></i>':j.trig?'<i class="ph '+TRIG[j.trig][0]+'"></i>':'')+'<span class="t">'+j.n+'</span>'+((j.tasks||[]).length?'<span class="k">'+j.tasks.length+'</span>':'')+(tools.length?'<span class="tl">'+tools.slice(0,4).map(x=>'<span class="pg" style="--cov:'+Math.round((x.cov||0)*100)+'%"></span>').join('')+'</span>':'')+(F.length?'<span class="pin">'+F.length+'</span>':'')+(j.q?'<span class="qm">?</span>':'')+'<span class="port"></span>';
      c.onclick=e=>{ e.stopPropagation(); if(connectMode){ const from=connectMode; connectMode=null; if(from!==j.id) sheetHandoffFrom(from,j.id); return; } if(e.shiftKey){ multi.has(j.id)?multi.delete(j.id):multi.add(j.id); render(); selbar(); return; } multi.clear(); select(j.id,'job'); }; c.oncontextmenu=e=>clipMenu(e,j);
      c.ondblclick=()=>sheetJob(j); c.querySelector('.port').onmousedown=ev=>{ev.stopPropagation();connectMode=j.id;document.body.style.cursor='crosshair';}; c.onmouseup=ev=>{ if(connectMode&&connectMode!==j.id){ const from=connectMode; connectMode=null; document.body.style.cursor=''; sheetHandoffFrom(from,j.id);} }; lane.appendChild(c); });
    // marquee on empty lane
    lane.oncontextmenu=e=>{ if(e.target.closest('.clip')) return; laneMenu(e,t,lane); };
    lane.onmousedown=e=>{ if(e.target!==lane||e.button!==0) return; const r=$('#tls').getBoundingClientRect(); const sx=e.clientX,sy=e.clientY; const mq=document.createElement('div'); mq.className='marq'; $('#tls').appendChild(mq); const mv=ev=>{ const x=Math.min(sx,ev.clientX)-r.left+$('#tls').scrollLeft,y=Math.min(sy,ev.clientY)-r.top+$('#tls').scrollTop; mq.style.left=x+'px'; mq.style.top=y+'px'; mq.style.width=Math.abs(ev.clientX-sx)+'px'; mq.style.height=Math.abs(ev.clientY-sy)+'px'; const box={l:Math.min(sx,ev.clientX),r:Math.max(sx,ev.clientX),t:Math.min(sy,ev.clientY),b:Math.max(sy,ev.clientY)}; multi.clear(); $$('.clip').forEach(cl=>{ const b=cl.getBoundingClientRect(); if(b.right>box.l&&b.left<box.r&&b.bottom>box.t&&b.top<box.b) multi.add(cl.dataset.job); cl.classList.toggle('multi',multi.has(cl.dataset.job)); }); }; const up=()=>{ mq.remove(); document.removeEventListener('mousemove',mv); document.removeEventListener('mouseup',up); if(multi.size){ sel=null; outline(); selbar(); } }; document.addEventListener('mousemove',mv); document.addEventListener('mouseup',up); };
    el.appendChild(d); });
  const dr=document.createElement('div'); dr.className='drop-row'; dr.innerHTML='<div class="h"><i class="ph ph-plus"></i>someone</div><div></div>'; dr.onclick=e=>addMenu(e,null); el.appendChild(dr);
  // regions: hull around members
  requestAnimationFrame(()=>{ REGIONS.forEach(rg=>{ const els=rg.members.map(id=>$('.clip[data-job="'+id+'"]')).filter(Boolean); if(!els.length) return; const er=el.getBoundingClientRect(); let l=1e9,r=-1e9,t=1e9,b=-1e9; els.forEach(x=>{const bb=x.getBoundingClientRect(); l=Math.min(l,bb.left);r=Math.max(r,bb.right);t=Math.min(t,bb.top);b=Math.max(b,bb.bottom);}); const d=document.createElement('div'); d.className='region'; d.style.setProperty('--c',rg.c); d.style.left=((l-er.left)/zoomv-10)+'px'; d.style.top=((t-er.top)/zoomv-10)+'px'; d.style.width=((r-l)/zoomv+20)+'px'; d.style.height=((b-t)/zoomv+20)+'px'; d.innerHTML='<span class="rt" onclick="sheetRegion(\''+rg.id+'\')">'+rg.n+'</span>'; el.appendChild(d); });
    const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'); svg.setAttribute('class','wires'); el.appendChild(svg); WIRES.forEach(([a,b,k])=>{ const A=$('.clip[data-job="'+a+'"]'),B=$('.clip[data-job="'+b+'"]'); if(!A||!B) return; const r=el.getBoundingClientRect(),ra=A.getBoundingClientRect(),rb=B.getBoundingClientRect(); const ax=(ra.right-r.left)/zoomv,ay=(ra.top+ra.height/2-r.top)/zoomv,bx=(rb.left-r.left)/zoomv,by=(rb.top+rb.height/2-r.top)/zoomv,m=(ax+bx)/2; const p=document.createElementNS('http://www.w3.org/2000/svg','path'); p.setAttribute('class','w'+(k?' '+k:'')+((a===sel||b===sel)?' near':'')); p.setAttribute('d','M'+ax+' '+ay+' C '+m+' '+ay+','+m+' '+by+','+bx+' '+by); svg.appendChild(p); }); });
  el.classList.toggle('dim',!!sel&&selKind==='job'||needOnly); WIRES.forEach(([a,b])=>{ if(a===sel) $('.clip[data-job="'+b+'"]')?.classList.add('near'); if(b===sel) $('.clip[data-job="'+a+'"]')?.classList.add('near'); }); if(needOnly) $$('.clip').forEach(c=>{ if(findings(job(c.dataset.job)).length) c.classList.add('near'); }); document.body.classList.toggle('present',view==='present'); selbar(); }
function selbar(){ const b=$('#selbar'); if(multi.size<2){ b.classList.remove('show'); return; } const els=[...multi].map(id=>$('.clip[data-job="'+id+'"]')).filter(Boolean); if(!els.length){ b.classList.remove('show'); return; } const r=$('#tls').getBoundingClientRect(); let l=1e9,t=1e9; els.forEach(x=>{const bb=x.getBoundingClientRect(); l=Math.min(l,bb.left); t=Math.min(t,bb.top);}); b.style.left=(l-r.left+$('#tls').scrollLeft)+'px'; b.style.top=(t-r.top+$('#tls').scrollTop-40)+'px';
  const tracks=new Set([...multi].map(id=>job(id).t)); const joint=tracks.size>1&&[...tracks].some(x=>track(x).k==='agent')&&[...tracks].some(x=>track(x).k==='person');
  b.innerHTML='<button onclick="groupRegion()"><i class="ph ph-bookmark-simple"></i>Region</button>'+(joint?'<button onclick="toast(\'Joint work: the agent job, the person decision, and the gate between\')"><i class="ph ph-scales"></i>Joint work</button>':'<button onclick="groupJob()"><i class="ph ph-rectangle"></i>Into a job</button>')+'<button onclick="collectAgent()"><i class="ph ph-robot"></i>For an agent</button><span class="sp"></span><button onclick="toast(\'Move to…\')"><i class="ph ph-arrows-left-right"></i></button><button onclick="snap();JOBS=JOBS.filter(j=>!multi.has(j.id));multi.clear();render()"><i class="ph ph-x"></i></button>'; b.classList.add('show'); }
function groupRegion(){ sheetRegion(null,[...multi]); }
function groupJob(){ const ids=[...multi]; const tr=track(job(ids[0]).t); sheet('Into one job',[['n','What does a person get?','three to five words'],['for','Who is waiting on it?','']],v=>{ snap(); const kids=ids.map(job); const nj={id:'j'+Date.now(),t:tr.id,c:Math.min(...kids.map(k=>k.c)),n:v.n||'New job',for:v.for,trig:kids[0].trig,tasks:kids.flatMap(k=>k.tasks.length?k.tasks:[{id:'t'+Math.random(),n:k.n,k:'look',tools:[]}])}; JOBS=JOBS.filter(j=>!ids.includes(j.id)).concat(nj); WIRES=WIRES.map(w=>[ids.includes(w[0])?nj.id:w[0],ids.includes(w[1])?nj.id:w[1],w[2]]).filter(w=>w[0]!==w[1]); multi.clear(); render(); select(nj.id,'job'); },'ph-rectangle'); }
function collectAgent(){ const ids=[...multi]; const kids=ids.map(job); const dec=kids.filter(k=>k.gate||(k.tasks||[]).some(t=>t.k==='decide')); const screen=kids.flatMap(k=>(k.tasks||[]).flatMap(t=>(t.tools||[]).filter(x=>x.cov!=null&&x.cov<.5))); sheet('For an agent',[['n','What does a person get?','name the job by its outcome'],['note',(dec.length?'Keeps a decision: '+dec.map(k=>k.n).join(', ')+' — the decision stays with a person.':'No decisions inside.')+(screen.length?' Tools an agent may not reach: '+screen.map(t=>t.n).join(', ')+'.':''),'','','note']],v=>{ snap(); const ag=TRACKS.find(t=>t.k==='agent')||TRACKS[0]; const nj={id:'j'+Date.now(),t:ag.id,c:Math.min(...kids.map(k=>k.c)),n:v.n||'Agent job',trig:'chain',tasks:kids.flatMap(k=>(k.tasks||[]).filter(t=>t.k!=='decide'))}; JOBS=JOBS.filter(j=>!ids.includes(j.id)).concat(nj); dec.forEach(k=>{ JOBS.push({id:'j'+Math.random(),t:k.t,c:nj.c+1,n:k.gate?k.gate.rule:'Decide',trig:'hand',gate:k.gate||{rule:'a person decides',who:track(k.t).n},tasks:(k.tasks||[]).filter(t=>t.k==='decide')}); }); WIRES=WIRES.map(w=>[ids.includes(w[0])?nj.id:w[0],ids.includes(w[1])?nj.id:w[1],w[2]]).filter(w=>w[0]!==w[1]); multi.clear(); render(); select(nj.id,'job'); },'ph-robot'); }
function sheetHandoffFrom(a,b){ sheet('What changes hands',[['name','From '+job(a).n+' to '+job(b).n+'…','a document, data, a decision, a message'],['kind','Which is it?',null,'doc',null,[['doc','ph-file-text','a document'],['data','ph-table','data'],['decision','ph-check-square','a decision'],['message','ph-envelope','a message']]]],v=>{ snap(); WIRES.push([a,b,track(job(b).t).k==='person'?'pull':'',v.name]); render(); select(b,'job'); },'ph-flow-arrow'); }
document.addEventListener('mouseup',()=>{ if(connectMode&&document.body.style.cursor==='crosshair'){ connectMode=null; document.body.style.cursor=''; } });
function sheetRegion(id,members){ const rg=id?REGIONS.find(r=>r.id===id):null; sheet(rg?'Region':'A region',[['n','Title','',rg?.n],['c','Colour',null,rg?.c||SW[REGIONS.length%SW.length],null,SW.map(c=>[c,'',''])]],v=>{ snap(); if(rg){ rg.n=v.n||rg.n; rg.c=v.c||rg.c; } else REGIONS.push({id:'r'+Date.now(),n:v.n||'Region',c:v.c||SW[0],members:members||[]}); multi.clear(); render(); },'ph-bookmark-simple'); }
$('#tls').addEventListener('click',e=>{ if(!e.target.closest('.clip')&&!e.target.closest('#selbar')&&!e.target.closest('.rt')){ multi.clear(); select(null,'board'); } });
function zoom(d){ zoomv=Math.min(1.6,Math.max(.5,zoomv+d*.1)); $('#tracks').style.transform='scale('+zoomv+')'; $('#tracks').style.transformOrigin='0 0'; timeline(); }
function fit(){ zoomv=Math.min(1,($('#tls').clientWidth-40)/$('#tracks').scrollWidth); $('#tracks').style.transform='scale('+zoomv+')'; $('#tracks').style.transformOrigin='0 0'; timeline(); }
$$('#views .ib').forEach(b=>b.onclick=()=>{ view=b.dataset.v; $$('#views .ib').forEach(x=>x.classList.toggle('on',x===b)); timeline(); toast(b.dataset.tip); });
/* ===== sheets ===== */
function sheet(title,fields,onDone,icon){ const V=$('#veil'); V.innerHTML='<div class="sheet"><div class="sh"><i class="ph '+(icon||'ph-pencil-simple')+'"></i>'+title+'</div><div class="sb">'+fields.map(([k,l,hint,val,type,opts])=>type==='note'?'<div class="fl"><div class="hint">'+l+'</div></div>':'<div class="fl"><label>'+l+'</label>'+(hint&&!opts?'<div class="hint">'+hint+'</div>':'')+(opts?'<div class="opts" data-k="'+k+'">'+opts.map(([v,i,t])=>'<span class="opt '+(val===v?'on':'')+'" data-v="'+v+'" '+(t?'':'style="width:26px;height:26px;padding:0;border-radius:50%;background:'+v+';border-color:'+(val===v?'#fff':'transparent')+'"')+'>'+(i?'<i class="ph '+i+'"></i>':'')+t+'</span>').join('')+'</div>':type==='area'?'<textarea data-k="'+k+'">'+(val||'')+'</textarea>':'<input data-k="'+k+'" value="'+(val||'')+'" placeholder="'+(hint||'')+'">')+'</div>').join('')+'</div><div class="sf"><button class="bt q" onclick="closeSheet()">Cancel</button><button class="bt acc" id="sh-ok"><i class="ph ph-check"></i>Done</button></div></div>'; V.classList.add('show');
  $$('.opts .opt',V).forEach(o=>o.onclick=()=>{$$('.opt',o.parentElement).forEach(x=>{x.classList.remove('on'); if(x.style.background) x.style.borderColor='transparent';});o.classList.add('on'); if(o.style.background) o.style.borderColor='#fff';}); const first=$('input,textarea',V); if(first) setTimeout(()=>first.focus(),0);
  $('#sh-ok').onclick=()=>{ const v={}; $$('[data-k]',V).forEach(el=>{ if(el.classList.contains('opts')) v[el.dataset.k]=$('.opt.on',el)?.dataset.v; else v[el.dataset.k]=el.value; }); closeSheet(); onDone(v); }; V.onkeydown=e=>{ if(e.key==='Escape') closeSheet(); if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA'){e.preventDefault();$('#sh-ok').click();} }; }
function closeSheet(){ $('#veil').classList.remove('show'); $('#veil').innerHTML=''; }
function sheetJob(j){ sheet(j.n||'This job',[['n','What does a person get?','three to five words',j.n],['o','What is different when it\'s done?','in their words',j.o,'area'],['for','Who is waiting on it?','',j.for],['d','Done when…','what would you check?',j.d],['trig','It starts',null,j.trig||'hand',null,Object.entries(TRIG).map(([k,[i,l]])=>[k,i,l])]],v=>{ snap(); Object.assign(j,{n:v.n||j.n,o:v.o,for:v.for,d:v.d,trig:v.trig}); render(); },'ph-rectangle'); }
function sheetTask(j,x){ sheet(x.n||'This task',[['n','What do you do?','as you would tell a new colleague',x.n],['k','What kind of work is it?',null,x.k,null,Object.entries(KIND).map(([k,l])=>[k,KI(k),l])],['how','What do you open, how far do you read, when do you stop?','and what you do when it isn\'t there',x.how,'area'],['chk','What must be true when this is done?','a check; say what happens when it fails',x.chk]],v=>{ snap(); Object.assign(x,{n:v.n||x.n,k:v.k||x.k,how:v.how,chk:v.chk||x.chk}); render(); },KI(x.k)); }
function sheetGate(j){ sheet('A decision',[['rule','What decides here?','in words',j.gate?.rule],['who','Who answers for it?','a person, or a rule with an owner',j.gate?.who]],v=>{ snap(); j.gate={rule:v.rule,who:v.who}; render(); },'ph-scales'); }
function toast(t){ const e=$('#toast'); e.textContent=t; e.style.display='block'; clearTimeout(e._t); e._t=setTimeout(()=>e.style.display='none',2400); }
document.addEventListener('click',e=>{ if(!e.target.closest('.pop')) $('#pop').classList.remove('show'); });
document.addEventListener('keydown',e=>{ if(e.target.matches('input,textarea')) return; if(e.key==='a'&&sel&&selKind==='job'){ connectMode=sel; toast('Click the job it hands to'); return; } if(e.key==='g'&&sel&&selKind==='job'){ sheetGate(job(sel)); return; } if(e.key==='t'&&sel&&selKind==='job'){ addThing('task',sel); return; } if((e.key==='Backspace'||e.key==='Delete')&&sel&&selKind==='job'){ snap(); JOBS=JOBS.filter(x=>x.id!==sel); WIRES=WIRES.filter(w=>w[0]!==sel&&w[1]!==sel); selectNone(); return; } if(e.key==='r'&&sel&&selKind==='job'){ e.preventDefault(); const inp=$('.raise input'); if(inp){ inp.focus(); return; } } if((e.metaKey||e.ctrlKey)&&e.key==='z'){ e.preventDefault(); undo(); } if(e.key==='Escape'){ closeSheet(); multi.clear(); select(null,'board'); toggleAsk(false); } });
let focus=null; const FULL={};
function mini(){ const m=$('#mini'); if(!m) return; const w=880; const ncol=Math.max(...JOBS.map(j=>j.c))+1; m.innerHTML=TRACKS.map(t=>'<div class="row"><span class="who"><i class="ph '+WHOI[t.k]+'"></i>'+t.n+'</span><div class="lane">'+JOBS.filter(j=>j.t===t.id).map(j=>'<span class="c '+(j.q?'q':'')+'" style="--c:'+WHOC[t.k]+';left:'+Math.round(j.c*(w/ncol))+'px" onclick="openBoard(\''+j.id+'\')">'+j.n+(findings(j).length?'<i>'+findings(j).length+'</i>':'')+'</span>').join('')+'</div></div>').join(''); }
function openBoard(id){ $('#rv').classList.remove('show'); select(id,'job'); }
function enterFocus(id){ const j=job(id); if(!j||!(j.tasks||[]).length) return; FULL.T=TRACKS;FULL.J=JOBS;FULL.W=WIRES;FULL.R=REGIONS; focus=id;
  const kids=j.tasks; const trs=[{id:'in',k:'outside',n:'Comes in',m:j.inputs?'':'from '+(WIRES.find(w=>w[1]===id)?job(WIRES.find(w=>w[1]===id)[0]).n:'the previous job')},track(j.t),{id:'out',k:'outside',n:'Goes out',m:'to '+(WIRES.find(w=>w[0]===id)?job(WIRES.find(w=>w[0]===id)[0===0?1:1]).n:'who is waiting')}];
  const js=[{id:'in',t:'in',c:0,n:j.for?'from the previous job':'the previous job',out:true,tasks:[]},...kids.map((t,i)=>({id:t.id,t:j.t,c:i+1,n:t.n,trig:i?'chain':'arrive',tasks:[],tk:t})),{id:'out',t:'out',c:kids.length+1,n:j.for||'who is waiting',out:true,tasks:[]}];
  const ws=[]; for(let i=0;i<js.length-1;i++) ws.push([js[i].id,js[i+1].id,i===0?'pull':'']);
  TRACKS=trs;JOBS=js;WIRES=ws;REGIONS=[]; $('#fb').classList.add('show'); $('#fbn').textContent=j.n; sel=null; render(); $('#stt').textContent='Focus'; $('#sh').innerHTML='<div><div class="crumb"><b onclick="leaveFocus()">the board</b><i class="ph ph-caret-right"></i>'+track(j.t).n+'</div><h2><i class="ph ph-arrows-in-simple"></i>'+j.n+'</h2><div class="sub">'+(j.o||'')+'</div><div class="chips"><span class="chip"><i class="ph ph-squares-four"></i><b>'+kids.length+'</b> tasks</span>'+(j.for?'<span class="chip"><i class="ph ph-user"></i><b>'+j.for+'</b></span>':'')+'</div></div>'; $('#sb').innerHTML='<div class="acct"><div class="f"><label>Inside this job only</label><div class="v" style="color:var(--t2)">Everything else is folded away. Select a task below to open it; drag tasks between rows to change who does them; ⌘Z undoes.</div></div></div>'; }
function leaveFocus(){ if(!focus) return; TRACKS=FULL.T;JOBS=FULL.J;WIRES=FULL.W;REGIONS=FULL.R; const f=focus; focus=null; $('#fb').classList.remove('show'); select(f,'job'); }
const _sel=select; select=function(id,k){ if(focus&&k==='job'&&job(id)&&job(id).tk){ sel=id; selKind='job'; render(); $('#stt').textContent='Task'; return; } _sel(id,k); };
document.addEventListener('keydown',e=>{ if(e.key==='Enter'&&sel&&selKind==='job'&&!focus&&!e.target.matches('input,textarea')) enterFocus(sel); });
const st=new URLSearchParams(location.search).get('state');
if(st==='review') { $('#rv').classList.add('show'); mini(); icons(); } else if(st==='focus'){ select('admit','job'); enterFocus('admit'); } else select(st==='triage'?'triage':'admit','job');
</script></body></html>'''
open('workspace-v4.html','w').write(html)
print(len(html)//1024,'KB')
